Install and Setup Devise for User Authentication
peter-akhigbe/microverse-rails-blog pull request #9
Opened 2023-12-22 23:26 UTC by peter-akhigbe

- Can register a new user. ✅
- User logs in with a combination of email and password. ✅
- Hashed password should be stored in the database. ✅
- Ask for confirmation of email. ✅
- Can reset password. ✅

- Remove current_user method in ApplicationController. ✅

2023-12-22 23:30 UTC, Olamarx requested changes
Hi @peter-akhigbe, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have passing linters, kindly fix it.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-12-23 00:33 UTC, Reem-lab commented
Hello @peter-akhigbe could you check your slack?

2023-12-23 00:44 UTC, peter-akhigbe commented
Hello @ reviewer

I did the project solo because of some issues with my coding partner.

Below is a screenshot of the email from Marco Lizza about the issue.

So please kindly disregard the collaboration requirements for this project

Thank you.

![image](https://github.com/peter-akhigbe/microverse-rails-blog/assets/12002619/940752d4-5e8f-47bd-a270-680eb73a43b8)

2023-12-23 01:54 UTC, Reem-lab requested changes
# Hi @peter-akhigbe, 👋🏻👋🏻 

Great job so far! 🔥✨💯⭐
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- [ ] No Linters error 🚀
- [ ] Followed GitFlow 💯
- [ ] Amazing job working on setup the devise👏🏻👏🏻




## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-23 01:54 UTC, Reem-lab commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable, :confirmable
- [ ] Great job for adding the confirmation after signing up I can see the user index page directly but it should lead me to a confirmation mail so after the confirmation I can log in 🎉🔥🚀


![image](https://github.com/lilskyex0x/Blog-app/assets/58553711/ca8d48ec-6be2-42e4-846c-bf74c812d455)

2023-12-23 10:51 UTC, topeogunleye approved these changes
### Hi @peter-akhigbe, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
Fantastic! 🎉 Here's a revised version of the code review feedback:

1. **Confirmation Implementation:**
   - Kudos on swiftly implementing the email confirmation step after signing up! 🚀 This will greatly enhance the security and reliability of user accounts.
   - Verify that users are now redirected to a confirmation mail before attempting to log in.

2. **Authentication Adjustment:**
   - Well done on adding the `authenticate_user!` method to the `ApplicationController`. This ensures that users need to confirm their email before gaining access, boosting the overall security of your application.

3. **User Experience Enhancement:**
   - The changes made contribute to a smoother and more secure user experience, aligning with best practices in user authentication and verification.

4. **Code Quality:**
   - Confirm that any relevant documentation has been updated to reflect the recent changes. Documentation is crucial for maintaining codebase clarity.
   - Double-check the implementation to ensure a seamless and user-friendly confirmation process.

5. **Celebration:**
   - 🎉 Outstanding work! Your responsiveness and dedication to improving the application are commendable. Keep up the excellent effort!
 
## [Optional] suggestions:
* Nothing to mention.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-23 11:08 UTC, merged